development:
  adapter: postgresql
  encoding: unicode
  database: gpsraceing
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gpsraceing_test
  pool: 5
  username: root 
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: gpsraceing_production
  pool: 5
  username: root 
  password: root
  host: localhost